In [41]:
import pandas as pd

pd.read_csv("evaluation-100.csv").sort_values("factual", ascending=False)

,model,factual,non_factual,unknown,failed,ents_per_sum,sum_with_extrinsic,rouge1,rouge2,rougeL
0,fbs_oracle,0.79,0.21,0.00,10,2.933333,0.46,0.463781,0.238510,0.389488
1,fbs_classifier,0.69,0.31,0.00,13,2.873563,0.41,0.455708,0.234311,0.381817
3,corrector,0.68,0.32,0.00,0,3.070000,0.61,0.461488,0.229356,0.389177
2,baseline,0.66,0.34,0.00,0,3.090000,0.61,0.461872,0.229120,0.389453
4,filtered,0.62,0.37,0.01,0,2.810000,0.58,0.445525,0.207173,0.373429

In [24]:
import pandas as pd

df = pd.read_json("evaluation-100-summaries.json")
df.head()

,fbs_oracle_summary,fbs_oracle_is_non_factual,fbs_oracle_is_factual,fbs_oracle_has_unknown,fbs_oracle_has_failed,fbs_oracle_n_extrinsic,fbs_classifier_summary,fbs_classifier_is_non_factual,fbs_classifier_is_factual,fbs_classifier_has_unknown,...,corrector_is_factual,corrector_has_unknown,corrector_has_failed,corrector_n_extrinsic,filtered_summary,filtered_is_non_factual,filtered_is_factual,filtered_has_unknown,filtered_has_failed,filtered_n_extrinsic
13810760,Former Ospreys scrum-half Mike Phillips has be...,False,True,False,False,1,Former Ospreys scrum-half Mike Phillips has be...,False,True,False,...,True,False,False,1,Wales scrum-half Mike Phillips has been suspen...,False,True,False,False,2
19626825,A public meeting has been held in Flintshire t...,False,True,False,False,0,Hundreds of people have attended a public meet...,True,False,False,...,False,False,False,1,A public meeting has been held to discuss plan...,False,True,False,False,0
21152677,The police ombudsman's office is to resume inv...,False,True,False,False,0,The police ombudsman's office is to resume inv...,False,True,False,...,False,False,False,1,The police ombudsman's office is to resume inv...,False,True,False,False,0
21958547,"The UK's Department for Environment, Food and ...",False,True,False,False,1,"The UK's Department for Environment, Food and ...",False,True,False,...,True,False,False,1,Pesticides used to control pests on crops are ...,False,True,False,False,0
22213813,The remote town of Mashkel is one of the most ...,False,True,False,False,1,The remote town of Mashkel is one of the most ...,False,True,False,...,True,False,False,1,Mashkel is one of the most remote towns in Pak...,False,True,False,False,1

In [38]:
# Helper method
def print_summaries(df, models):
    for sum_id in df.index:
        print(f"---XSUM ID {sum_id}---")
        row = df.loc[sum_id]
        for model in models:
            n_ents = row[model + '_n_extrinsic']
            summary = row[model + '_summary']
            print(f"{model} ({n_ents} extrinsic ents): {[summary]}")
        print()

### Summaries corrected by Oracle

In [48]:
df_inspect = df[
    df.fbs_oracle_is_factual
    & df.baseline_is_non_factual
]
print(df_inspect.shape[0])
print_summaries(
    df_inspect,
    [
        "baseline",
        "fbs_oracle"
    ]
)

13
---XSUM ID 19626825---
baseline (1 extrinsic ents): ['Hundreds of people have attended a public meeting in Flintshire to discuss plans to close a community hospital.']
fbs_oracle (0 extrinsic ents): ['A public meeting has been held in Flintshire to discuss plans to close a community hospital.']

---XSUM ID 21152677---
baseline (1 extrinsic ents): ['The police ombudsman is to resume investigations into more than 100 historical complaints against the PSNI.']
fbs_oracle (0 extrinsic ents): ["The police ombudsman's office is to resume investigations into more than 150 historical complaints against the PSNI."]

---XSUM ID 30768958---
baseline (1 extrinsic ents): ['A road in Stafford town centre is to be closed as part of a £1m project to replace water pipes.']
fbs_oracle (0 extrinsic ents): ['A road in Stafford town centre is to be closed as part of a £2.5m project to replace water pipes.']

---XSUM ID 33235610---
baseline (3 extrinsic ents): ['(Close): The pound rose against the euro and the dollar on Tuesday, after the Bank of England raised its interest rate to 0.5%.']
fbs_oracle (1 extrinsic ents): ["(Close): The pound rose against the euro and the dollar on Tuesday, following Monday's sharp gains."]

---XSUM ID 34320852---
baseline (2 extrinsic ents): ['The Scottish Football Association (SFA) is considering the future of its performance school programme, according to chief executive Martin McClair.']
fbs_oracle (1 extrinsic ents): ['The Scottish Football Association (SFA) is considering the future of its performance school programme.']

---XSUM ID 36122985---
baseline (1 extrinsic ents): ['A letter written by Princess Elizabeth describing her relationship with Prince Philip has sold at auction for more than £20,000.']
fbs_oracle (0 extrinsic ents): ['A letter written by Princess Elizabeth describing her relationship with Prince Philip has sold at auction for £14,400.']

---XSUM ID 36266180---
baseline (1 extrinsic ents): ['More than 1,500 savings rate cuts have been made by banks in the past year, the BBC has learned.']
fbs_oracle (1 extrinsic ents): ['More than 1,400 savings rate cuts have been made by banks in the past year, according to a new report.']

---XSUM ID 36396523---
baseline (3 extrinsic ents): ["Brazil have added Kaka to their squad for next month's Under-20 World Cup in South America."]
fbs_oracle (2 extrinsic ents): ['Kaka has been called up to the Brazil squad for the Copa America in Brazil in June.']

---XSUM ID 36516057---
baseline (3 extrinsic ents): ['The Conjuring 2 has topped the US and Canada box office for the second weekend in a row.']
fbs_oracle (2 extrinsic ents): ['The Conjuring 2 has topped the US and Canada box office for the first time since its release in 2013.']

---XSUM ID 37228816---
baseline (1 extrinsic ents): ['The second group of Syrian refugees have arrived in Londonderry.']
fbs_oracle (0 extrinsic ents): ['More Syrian refugees have arrived in Londonderry.']

---XSUM ID 37749695---
baseline (5 extrinsic ents): ["Tottenham midfielder Moussa Sissoko has been banned for four games for an elbow to the face of Stoke's Harry Arter."]
fbs_oracle (4 extrinsic ents): ['Tottenham midfielder Moussa Sissoko has been banned for three games for an elbow to the face of Harry Arter.']

---XSUM ID 38300624---
baseline (1 extrinsic ents): ['Rail passengers on the Borders to Edinburgh line have been told to expect delays of up to an hour and a half.']
fbs_oracle (1 extrinsic ents): ['Rail passengers on the Borders to Edinburgh line have been able to return to their homes after a day of disruption.']

---XSUM ID 40092224---
baseline (1 extrinsic ents): ['Police have said the death of a man at a hotel in Dundee is not being treated as suspicious.']
fbs_oracle (1 extrinsic ents): ['Police have said the death of a man at a hotel in Edinburgh is not being treated as suspicious.']

### Summaries messed by FBS Classifier

In [49]:
df_inspect = df[
    df.baseline_is_factual
    & df.fbs_classifier_is_non_factual
]

print(df_inspect.shape)
print_summaries(
    df_inspect,
    [
        "baseline",
        "fbs_classifier"
    ]
)

(2, 30)
---XSUM ID 33750803---
baseline (1 extrinsic ents): ['At least six people have been killed and more than 30 injured in a suicide bombing in northern Turkey, the army says.']
fbs_classifier (0 extrinsic ents): ['<Failed generation: blocked all beams>']

---XSUM ID 35011005---
baseline (1 extrinsic ents): ["Former Wales captain Martyn Williams says Dan Biggar's decision to sign a new contract with Ospreys will benefit the region."]
fbs_classifier (2 extrinsic ents): ["Dan Biggar's decision to sign a new four-year contract with Ospreys will help the region attract new players, according to former Wales captain Marti Williams."]

In [50]:
df_inspect = df[
    df.baseline_is_non_factual
    & df.fbs_classifier_is_factual
]

print(df_inspect.shape)
print_summaries(
    df_inspect,
    [
        "baseline",
        "fbs_classifier"
    ]
)

(5, 30)
---XSUM ID 21152677---
baseline (1 extrinsic ents): ['The police ombudsman is to resume investigations into more than 100 historical complaints against the PSNI.']
fbs_classifier (0 extrinsic ents): ["The police ombudsman's office is to resume investigations into more than 150 historical complaints against the PSNI."]

---XSUM ID 30768958---
baseline (1 extrinsic ents): ['A road in Stafford town centre is to be closed as part of a £1m project to replace water pipes.']
fbs_classifier (0 extrinsic ents): ['A road in Stafford town centre is to be closed as part of a £2.5m project to replace water pipes.']

---XSUM ID 33235610---
baseline (3 extrinsic ents): ['(Close): The pound rose against the euro and the dollar on Tuesday, after the Bank of England raised its interest rate to 0.5%.']
fbs_classifier (1 extrinsic ents): ["(Close): The pound rose against the euro and the dollar on Tuesday, following Monday's sharp gains."]

---XSUM ID 33262593---
baseline (0 extrinsic ents): ['A World War Two fighter jet that was used in the Gulf War has been put up for sale by two ex-RAF engineers.']
fbs_classifier (0 extrinsic ents): ['A couple who bought an RAF plane used in the Gulf War as a shell have put it up for sale.']

---XSUM ID 36122985---
baseline (1 extrinsic ents): ['A letter written by Princess Elizabeth describing her relationship with Prince Philip has sold at auction for more than £20,000.']
fbs_classifier (0 extrinsic ents): ['A letter written by Princess Elizabeth describing her relationship with Prince Philip has sold at auction for £14,400.']

### Summaries messed up by Filtered

In [42]:
df_inspect = df[
    df.baseline_is_factual
    & df.filtered_is_non_factual
]
print(df_inspect.shape[0])
print_summaries(
    df_inspect,
    [
        "baseline",
        "filtered"
    ]
)

13
---XSUM ID 27319850---
baseline (0 extrinsic ents): ['New fathers are often diagnosed with post-traumatic stress disorder (PTSD), a condition that can lead to depression and anxiety.']
filtered (3 extrinsic ents): ['The number of women who suffer from post-traumatic stress disorder (PTSD) is estimated to be one in five women in the UK.']

---XSUM ID 33750803---
baseline (1 extrinsic ents): ['At least six people have been killed and more than 30 injured in a suicide bombing in northern Turkey, the army says.']
filtered (2 extrinsic ents): ['A suicide bomber has attacked a police station in northern Turkey, killing at least five people and injuring more than 20, the Turkish army says.']

---XSUM ID 34886413---
baseline (0 extrinsic ents): ["Singer-songwriter Eska has won this year's Mercury Prize for his debut album Architect."]
filtered (3 extrinsic ents): ['Pioneering singer-songwriter Nick Clegg has won the Mercury Prize for his debut album, The Sound of Silence.']

---XSUM ID 34903577---
baseline (2 extrinsic ents): ['Donald Trump has won the Republican nomination for the US presidential election.']
filtered (2 extrinsic ents): ['Donald Trump has been the US president-elect for more than a year.']

---XSUM ID 35011005---
baseline (1 extrinsic ents): ["Former Wales captain Martyn Williams says Dan Biggar's decision to sign a new contract with Ospreys will benefit the region."]
filtered (2 extrinsic ents): ['Dan Biggar\'s decision to sign a new four-year contract with Ospreys is "fantastic news" for Welsh rugby, says former Wales captain Martyn Williams.']

---XSUM ID 35194695---
baseline (1 extrinsic ents): ['The white police officer accused of killing a black teenager in Chicago in 2014 has pleaded not guilty.']
filtered (2 extrinsic ents): ['A Chicago police officer has appeared in court charged with the murder of a black teenager who was shot 16 times in 2014.']

---XSUM ID 35748919---
baseline (0 extrinsic ents): ['A woman has been given a suspended jail sentence for defrauding a charity set up in memory of a Cumbrian teenager who died from cancer.']
filtered (1 extrinsic ents): ['A charity founder who helped raise thousands of pounds for a teenage girl who died from cancer has been given a suspended jail sentence.']

---XSUM ID 37406842---
baseline (0 extrinsic ents): ['Work has been suspended at a recycling plant in Bridgend county after a large fire broke out.']
filtered (1 extrinsic ents): ['About 1,000 tonnes of wood chip has been destroyed in a fire at a recycling plant in Bridgend county.']

---XSUM ID 37585188---
baseline (1 extrinsic ents): ['Colombian President Juan Manuel Santos has won the 2016 Nobel Peace Prize for his efforts to end more than five decades of armed conflict.']
filtered (1 extrinsic ents): ["Colombia's President Juan Manuel Santos has won the Nobel Peace Prize for his efforts to end the country's 50-year armed conflict."]

---XSUM ID 38196591---
baseline (1 extrinsic ents): ['A man has been airlifted to hospital after being injured in a fall in Snowdonia.']
filtered (1 extrinsic ents): ['A man has been airlifted to hospital after falling from a cliff in Gwynedd.']

---XSUM ID 38507828---
baseline (1 extrinsic ents): ['A man has been injured after he was attacked by a man armed with a knife in north Belfast.']
filtered (1 extrinsic ents): ['A man has been seriously injured in a knife attack in north London.']

---XSUM ID 39058386---
baseline (1 extrinsic ents): ['French centrist presidential candidate Emmanuel Macron has agreed to join forces with a former prime minister to fight far-right leader Marine Le Pen.']
filtered (2 extrinsic ents): ["French centrist presidential candidate Emmanuel Macron has agreed to join forces with a former prime minister who has announced he will not stand in next month's election."]

---XSUM ID 40810771---
baseline (1 extrinsic ents): ['John Dingledine does not look like the kind of person who would complain about his own work.']
filtered (1 extrinsic ents): ['"I don\'t think I\'ve ever had a conversation with someone who doesn\'t look like a hacker," says David Dingledine.']

### Summaries messed up by Corrector

In [47]:
df_inspect = df[
    df.baseline_is_factual
    & df.corrector_is_non_factual
]
print(df_inspect.shape[0])
print_summaries(
    df_inspect,
    [
        "baseline",
        "corrector"
    ]
)

1
---XSUM ID 35011005---
baseline (1 extrinsic ents): ["Former Wales captain Martyn Williams says Dan Biggar's decision to sign a new contract with Ospreys will benefit the region."]
corrector (1 extrinsic ents): ["Former Wales captain Scott Williams says Dan Biggar's decision to sign a new four-year contract with Ospreys will help the region."]